name: ditonton
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  provider: ^6.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  get_it: ^7.7.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  flutter_bloc: ^8.1.3
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  firebase_analytics: ^11.4.0

  about:
    path: about

  core:
    path: core

  tv:
    path: features/tv

  movies:
    path: features/movies

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.1.1
  sqflite_common_ffi: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/certificates/
