name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  get_it: ^7.7.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  flutter_bloc: ^8.1.3
  crypto: ^3.0.3

  movies:
    path: ../features/movies

  tv:
    path: ../features/tv

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.1.1
  sqflite_common_ffi: ^2.3.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - certificates/
