// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARVTBtV7PBsY5I0S6JlRXOMVboBz2Y1LQ',
    appId: '1:959349096253:web:85374ff818d5fde3f08f54',
    messagingSenderId: '959349096253',
    projectId: 'ditonton-90c0b',
    authDomain: 'ditonton-90c0b.firebaseapp.com',
    storageBucket: 'ditonton-90c0b.firebasestorage.app',
    measurementId: 'G-YPZP97T7WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj7YxaBL1WPF4jK59N03Mk95484OkBkDA',
    appId: '1:959349096253:android:b84b257f8835b65ff08f54',
    messagingSenderId: '959349096253',
    projectId: 'ditonton-90c0b',
    storageBucket: 'ditonton-90c0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5v7NKUmQszJyfpTXTNir9qoUW7bLOr2Y',
    appId: '1:959349096253:ios:bbd9cb85b6e0f2d6f08f54',
    messagingSenderId: '959349096253',
    projectId: 'ditonton-90c0b',
    storageBucket: 'ditonton-90c0b.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
