library tv;

// data
// datasources
export 'data/datasources/tv_local_data_source.dart';
export 'data/datasources/tv_remote_data_source.dart';
// models
export 'data/models/tv_detail_model.dart';
export 'data/models/tv_model.dart';
export 'data/models/tv_response.dart';
export 'data/models/tv_table.dart';
// repositories
export 'data/repositories/tv_repository_impl.dart';

// domain
// entities
export 'domain/entities/tv.dart';
export 'domain/entities/tv_detail.dart';
// repositories
export 'domain/repositories/tv_repository.dart';
// usecases
export 'domain/usecases/get_on_the_air_tv.dart';
export 'domain/usecases/get_popular_tv.dart';
export 'domain/usecases/get_top_rated_tv.dart';
export 'domain/usecases/get_tv_detail.dart';
export 'domain/usecases/get_tv_recommendations.dart';
export 'domain/usecases/get_watchlist_status_tv.dart';
export 'domain/usecases/get_watchlist_tv.dart';
export 'domain/usecases/remove_watchlist_tv.dart';
export 'domain/usecases/save_watchlist_tv.dart';
export 'domain/usecases/search_tv.dart';

// presentation
// pages
export 'presentation/pages/home_tv_page.dart';
export 'presentation/pages/popular_tv_page.dart';
export 'presentation/pages/top_rated_tv_page.dart';
export 'presentation/pages/tv_detail_page.dart';
export 'presentation/pages/tv_search_page.dart';
export 'presentation/pages/watchlist_tv_page.dart';

// bloc
export 'presentation/bloc/on_the_air_tv/on_the_air_tv_bloc.dart';
export 'presentation/bloc/on_the_air_tv/on_the_air_tv_event.dart';
export 'presentation/bloc/on_the_air_tv/on_the_air_tv_state.dart';
export 'presentation/bloc/popular_tv/popular_tv_bloc.dart';
export 'presentation/bloc/popular_tv/popular_tv_event.dart';
export 'presentation/bloc/popular_tv/popular_tv_state.dart';
export 'presentation/bloc/search_tv/search_tv_bloc.dart';
export 'presentation/bloc/search_tv/search_tv_event.dart';
export 'presentation/bloc/search_tv/search_tv_state.dart';
export 'presentation/bloc/top_rated_tv/top_rated_tv_bloc.dart';
export 'presentation/bloc/top_rated_tv/top_rated_tv_event.dart';
export 'presentation/bloc/top_rated_tv/top_rated_tv_state.dart';
export 'presentation/bloc/tv_detail/tv_detail_bloc.dart';
export 'presentation/bloc/tv_detail/tv_detail_event.dart';
export 'presentation/bloc/tv_detail/tv_detail_state.dart';
export 'presentation/bloc/watchlist_tv/watchlist_tv_bloc.dart';
export 'presentation/bloc/watchlist_tv/watchlist_tv_event.dart';
export 'presentation/bloc/watchlist_tv/watchlist_tv_state.dart';

// widgets
export 'presentation/widgets/tv_card_list.dart';
